site_name: OpenStack Docs
site_url: https://jade-kinx.github.io/openstack-docs/
site_author: Jade Keith
site_description: Openstack documents repository for jade
# Repository
repo_name: jade-kinx/openstack-docs
repo_url: https://github.com/jade-kinx/openstack-docs/

extra_css:
  - assets/css/extra.css

copyright: KINX Inc. All Rights Reserved.
extra:
  generator: false

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Noto Sans KR
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - glightbox:
      effect: zoom
      width: 100%
      height: auto
      auto_caption: true
      caption_position: bottom

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - tables
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - inc/glossary.md
  - pymdownx.tilde
   
nav:
  - Home:
    - index.md
    - Usage: usage.md
  - OpenStack:
    - Overview: openstack/overview.md
    - Trove: 
      - Install Trove in DevStack: openstack/trove/install-trove-in-devstack.md
      - Commands: 
        - (sample)database instance list: openstack/trove/commands/database-instance-list.md
        - database db list: openstack/trove/commands/database-db-list.md
        - datastore list: openstack/trove/commands/datastore-list.md
        - database backup create: openstack/trove/commands/not-ready-yet.md
        - database backup delete: openstack/trove/commands/not-ready-yet.md
        - database backup execution delete: openstack/trove/commands/not-ready-yet.md
        - database backup list: openstack/trove/commands/not-ready-yet.md
        - database backup show: openstack/trove/commands/not-ready-yet.md
        - database backup strategy create: openstack/trove/commands/not-ready-yet.md
        - database backup strategy delete: openstack/trove/commands/not-ready-yet.md
        - database backup strategy list: openstack/trove/commands/not-ready-yet.md
        - database cluster create: openstack/trove/commands/not-ready-yet.md
        - database cluster delete: openstack/trove/commands/not-ready-yet.md
        - database cluster force create: openstack/trove/commands/not-ready-yet.md
        - database cluster grow: openstack/trove/commands/not-ready-yet.md
        - database cluster list: openstack/trove/commands/not-ready-yet.md
        - database cluster list instances: openstack/trove/commands/not-ready-yet.md
        - database cluster modules: openstack/trove/commands/not-ready-yet.md
        - database cluster reset status: openstack/trove/commands/not-ready-yet.md
        - database cluster show: openstack/trove/commands/not-ready-yet.md
        - database cluster shrink: openstack/trove/commands/not-ready-yet.md
        - database cluster upgrade: openstack/trove/commands/not-ready-yet.md
        - database configuration attach: openstack/trove/commands/not-ready-yet.md
        - database configuration create: openstack/trove/commands/not-ready-yet.md
        - database configuration default: openstack/trove/commands/not-ready-yet.md
        - database configuration delete: openstack/trove/commands/not-ready-yet.md
        - database configuration detach: openstack/trove/commands/not-ready-yet.md
        - database configuration instances: openstack/trove/commands/not-ready-yet.md
        - database configuration list: openstack/trove/commands/not-ready-yet.md
        - database configuration set: openstack/trove/commands/not-ready-yet.md
        - database configuration show: openstack/trove/commands/not-ready-yet.md
        - database db create: openstack/trove/commands/not-ready-yet.md
        - database db delete: openstack/trove/commands/not-ready-yet.md
        - database db list: openstack/trove/commands/not-ready-yet.md
        - database flavor list: openstack/trove/commands/not-ready-yet.md
        - database flavor show: openstack/trove/commands/not-ready-yet.md
        - database instance create: openstack/trove/commands/not-ready-yet.md
        - database instance delete: openstack/trove/commands/not-ready-yet.md
        - database instance detach: openstack/trove/commands/not-ready-yet.md
        - database instance eject: openstack/trove/commands/not-ready-yet.md
        - database instance force delete: openstack/trove/commands/not-ready-yet.md
        - database instance list: openstack/trove/commands/not-ready-yet.md
        - database instance promot: openstack/trove/commands/not-ready-yet.md
        - database instance reboot: openstack/trove/commands/not-ready-yet.md
        - database instance rebuild: openstack/trove/commands/not-ready-yet.md
        - database instance reset status: openstack/trove/commands/not-ready-yet.md
        - database instance resize flavor: openstack/trove/commands/not-ready-yet.md
        - database instance reisze volume: openstack/trove/commands/not-ready-yet.md
        - database instance restart: openstack/trove/commands/not-ready-yet.md
        - database instance show: openstack/trove/commands/not-ready-yet.md
        - database instance update: openstack/trove/commands/not-ready-yet.md
        - database instance upgrade: openstack/trove/commands/not-ready-yet.md
        - database limit list: openstack/trove/commands/not-ready-yet.md
        - database user create: openstack/trove/commands/not-ready-yet.md
        - database user delete: openstack/trove/commands/not-ready-yet.md
        - database user grant access: openstack/trove/commands/not-ready-yet.md
        - database user revoke access: openstack/trove/commands/not-ready-yet.md
        - database user list: openstack/trove/commands/not-ready-yet.md
        - database user show: openstack/trove/commands/not-ready-yet.md
        - database user show access: openstack/trove/commands/not-ready-yet.md
        - database user update attributes: openstack/trove/commands/not-ready-yet.md
        - database root disable: openstack/trove/commands/not-ready-yet.md
        - database root enable: openstack/trove/commands/not-ready-yet.md
        - database root show: openstack/trove/commands/not-ready-yet.md
        - datastore delete: openstack/trove/commands/not-ready-yet.md
        - datastore list: openstack/trove/commands/not-ready-yet.md
        - datastore show: openstack/trove/commands/not-ready-yet.md
        - datastore version create: openstack/trove/commands/not-ready-yet.md
        - datastore version delete: openstack/trove/commands/not-ready-yet.md
        - datastore version list: openstack/trove/commands/not-ready-yet.md
        - datastore version set: openstack/trove/commands/not-ready-yet.md
        - datastore version show: openstack/trove/commands/not-ready-yet.md


  - Useful Links:
    - links.md
    - mkdocs-material:
      - Home: https://squidfunk.github.io/mkdocs-material/
      - Getting Started: https://squidfunk.github.io/mkdocs-material/getting-started/
      - Setup: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
      - Reference: https://squidfunk.github.io/mkdocs-material/reference/
    - OpenStack:
      - docs.openstack.org: https://docs.openstack.org      